import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <header className="px-8 py-5">
        <div className="flex justify-between border-y-2 py-2">
          <span>GEOMAN.AI</span>
          <span className="lg:ml-[20em]">SOLUTIONS</span>
          <span>PROJECTS</span>
        </div>
        <div className="flex justify-between py-2 items-center mb-5 ">
          <p className="lg:max-w-[150px] lg:text-lg font-extrabold text-sm max-w-[90px]">
            REAL TIME MANAGEMENT AND ANALYSIS
          </p>
          <p className=" lg:ml-[15.5em] max-w-[50px] text-sm lg:text-lg">
            <span className="after:content-['•◦'] after:ml-2 after:text-[25px]">
              HIGH
            </span>{" "}
            QUALITY
          </p>
          <button
            className=" uppercase font-extrabold tracking-wide text-xs
         text-slate-900 bg-white rounded-full lg:px-5 lg:py-4 border
         border-slate-400 hover:border-black transition ease-linear duration-150 cursor-pointer px-3 py-2 "
          >
            GET STARTED
          </button>
        </div>
      </header>
      <main className="px-8">
        <div className="images-container flex gap-10 flex-col lg:flex-row h-screen lg:h-[500px] ">
          <div className="left-image lg:basis-2/3  relative  rounded-2xl basis-1/2">
            <Image
              src="/banana.jpg"
              fill
              className="object-cover rounded-2xl"
            />
            <div
              className="absolute z-20 bottom-5 text-black lg:right-10 flex items-center lg:gap-11
             border border-black rounded-full lg:px-8 lg:py-3 cursor-pointer
             right-4 py-1 text-sm px-5 gap-3 lg:text-lg  font-bold "
            >
              <span>Get expert advise</span>
              <FontAwesomeIcon
                icon={faArrowRight}
                className="text-sm bg-black text-white p-2 rounded-full lg:p-3 lg:text-lg"
              />
            </div>
            <div className="absolute left-10 lg:bottom-5 top-5 text-black font-bold lg:text-lg w-[200px] z-10 ">
              <h3>BECAUSE YOUR BUSSINESS NEEDS ALOT MORE</h3>
            </div>
          </div>
          <div className="right-image lg:basis-1/3 relative rounded-2xl basis-1/2 ">
            <div className="absolute z-10 font-bold lg:text-4xl text-center top-5 lg:left-[30%] text-3xl left-[33%]">
              The{" "}
              <span className="font-playFair block mt-3 lg:text-[1.5em]">
                Future
              </span>
            </div>
            <Image
              src="/pineapple.jpg"
              fill
              className="object-cover rounded-2xl"
            />
            <div className="absolute z-10 bottom-5 lg:left-[35%] w-[170px]  font-bold lg:text-lg text-center left-[25%]">
              Free your mind for something <strong>more IMPORTANT</strong>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
